common: &default_settings
# The agent uses its own log file to keep its logging
  # separate from that of your application. Specify the log level here.
  # This setting is dynamic, so changes do not require restarting your application.
  # The levels in increasing order of verboseness are:
  # off, severe, warning, info, fine, finer, finest
  # Default is info.
  log_level: finest

  # Log all data sent to and from New Relic in plain text.
  # This setting is dynamic, so changes do not require restarting your application.
  # Default is false.
  audit_mode: true

  agent_enabled: true